//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Data.Objects.DataClasses
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERP.Agendamento.Dados.AgendamentoSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERP.Agendamento.Dados.PacienteSet))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERP.Agendamento.Dados.AgendamentoSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERP.Agendamento.Dados.PacienteSet))]
    public partial class EntityObject : System.Data.Objects.DataClasses.StructuralObject
    {
        
        private System.Data.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfPacienteSetV0nggS78", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    public partial class EntityReferenceOfPacienteSetV0nggS78 : System.Data.Objects.DataClasses.EntityReference
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfPacienteSetV0nggS78))]
    public partial class EntityReference : System.Data.Objects.DataClasses.RelatedEnd
    {
        
        private System.Data.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfPacienteSetV0nggS78))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
}
namespace ERP.Agendamento.Dados
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgendamentoSet", Namespace="http://schemas.datacontract.org/2004/07/ERP.Agendamento.Dados", IsReference=true)]
    public partial class AgendamentoSet : System.Data.Objects.DataClasses.EntityObject
    {
        
        private System.DateTime DatahoraField;
        
        private string DescricaoField;
        
        private string EstadoField;
        
        private int IdField;
        
        private int Medico_IdField;
        
        private ERP.Agendamento.Dados.PacienteSet PacienteSetField;
        
        private System.Data.Objects.DataClasses.EntityReferenceOfPacienteSetV0nggS78 PacienteSetReferenceField;
        
        private int Paciente_IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datahora
        {
            get
            {
                return this.DatahoraField;
            }
            set
            {
                this.DatahoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao
        {
            get
            {
                return this.DescricaoField;
            }
            set
            {
                this.DescricaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Medico_Id
        {
            get
            {
                return this.Medico_IdField;
            }
            set
            {
                this.Medico_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.Agendamento.Dados.PacienteSet PacienteSet
        {
            get
            {
                return this.PacienteSetField;
            }
            set
            {
                this.PacienteSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReferenceOfPacienteSetV0nggS78 PacienteSetReference
        {
            get
            {
                return this.PacienteSetReferenceField;
            }
            set
            {
                this.PacienteSetReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Paciente_Id
        {
            get
            {
                return this.Paciente_IdField;
            }
            set
            {
                this.Paciente_IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteSet", Namespace="http://schemas.datacontract.org/2004/07/ERP.Agendamento.Dados", IsReference=true)]
    public partial class PacienteSet : System.Data.Objects.DataClasses.EntityObject
    {
        
        private string AfiliacaoMaeField;
        
        private string AfiliacaoPaiField;
        
        private ERP.Agendamento.Dados.AgendamentoSet[] AgendamentoSetsField;
        
        private int AlturaField;
        
        private System.Nullable<int> ConvenioField;
        
        private string CpfField;
        
        private System.DateTime DataNascimentoField;
        
        private string EnderecoComercialField;
        
        private string EnderecoResidencialField;
        
        private int IdField;
        
        private string NomeField;
        
        private int PesoField;
        
        private string RgField;
        
        private string SexoField;
        
        private string TelefoneCelularField;
        
        private string TelefoneComercialField;
        
        private string TelefoneResidencialField;
        
        private string TipoSanguineoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AfiliacaoMae
        {
            get
            {
                return this.AfiliacaoMaeField;
            }
            set
            {
                this.AfiliacaoMaeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AfiliacaoPai
        {
            get
            {
                return this.AfiliacaoPaiField;
            }
            set
            {
                this.AfiliacaoPaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ERP.Agendamento.Dados.AgendamentoSet[] AgendamentoSets
        {
            get
            {
                return this.AgendamentoSetsField;
            }
            set
            {
                this.AgendamentoSetsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Altura
        {
            get
            {
                return this.AlturaField;
            }
            set
            {
                this.AlturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Convenio
        {
            get
            {
                return this.ConvenioField;
            }
            set
            {
                this.ConvenioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpf
        {
            get
            {
                return this.CpfField;
            }
            set
            {
                this.CpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento
        {
            get
            {
                return this.DataNascimentoField;
            }
            set
            {
                this.DataNascimentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoComercial
        {
            get
            {
                return this.EnderecoComercialField;
            }
            set
            {
                this.EnderecoComercialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoResidencial
        {
            get
            {
                return this.EnderecoResidencialField;
            }
            set
            {
                this.EnderecoResidencialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Peso
        {
            get
            {
                return this.PesoField;
            }
            set
            {
                this.PesoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rg
        {
            get
            {
                return this.RgField;
            }
            set
            {
                this.RgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneCelular
        {
            get
            {
                return this.TelefoneCelularField;
            }
            set
            {
                this.TelefoneCelularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneComercial
        {
            get
            {
                return this.TelefoneComercialField;
            }
            set
            {
                this.TelefoneComercialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelefoneResidencial
        {
            get
            {
                return this.TelefoneResidencialField;
            }
            set
            {
                this.TelefoneResidencialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoSanguineo
        {
            get
            {
                return this.TipoSanguineoField;
            }
            set
            {
                this.TipoSanguineoField = value;
            }
        }
    }
}
namespace System.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EntityContainerNameField;
        
        private System.Data.EntityKeyMember[] EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName
        {
            get
            {
                return this.EntityContainerNameField;
            }
            set
            {
                this.EntityContainerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKeyMember[] EntityKeyValues
        {
            get
            {
                return this.EntityKeyValuesField;
            }
            set
            {
                this.EntityKeyValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName
        {
            get
            {
                return this.EntitySetNameField;
            }
            set
            {
                this.EntitySetNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReferenceOfPacienteSetV0nggS78))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERP.Agendamento.Dados.PacienteSet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERP.Agendamento.Dados.AgendamentoSet[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERP.Agendamento.Dados.AgendamentoSet))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private object ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="IProvedorServiços")]
public interface IProvedorServiços
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IProvedorServiços/Agendamento_Paciente", ReplyAction="http://Microsoft.ServiceModel.Samples/IProvedorServiços/Agendamento_PacienteRespo" +
        "nse")]
    ERP.Agendamento.Dados.PacienteSet Agendamento_Paciente(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IProvedorServiços/RH_MedicoEspecialidade", ReplyAction="http://Microsoft.ServiceModel.Samples/IProvedorServiços/RH_MedicoEspecialidadeRes" +
        "ponse")]
    string[] RH_MedicoEspecialidade(int cod_especialidade);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IProvedorServiços/RH_Especialidade", ReplyAction="http://Microsoft.ServiceModel.Samples/IProvedorServiços/RH_EspecialidadeResponse")]
    string[] RH_Especialidade();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IProvedorServiços/Administracao_PlanoSaude", ReplyAction="http://Microsoft.ServiceModel.Samples/IProvedorServiços/Administracao_PlanoSaudeR" +
        "esponse")]
    string[] Administracao_PlanoSaude();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IProvedorServiços/Financeiro_SolicitarPagam" +
        "ento", ReplyAction="http://Microsoft.ServiceModel.Samples/IProvedorServiços/Financeiro_SolicitarPagam" +
        "entoResponse")]
    int Financeiro_SolicitarPagamento();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IProvedorServiçosChannel : IProvedorServiços, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProvedorServiçosClient : System.ServiceModel.ClientBase<IProvedorServiços>, IProvedorServiços
{
    
    public ProvedorServiçosClient()
    {
    }
    
    public ProvedorServiçosClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ProvedorServiçosClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProvedorServiçosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProvedorServiçosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ERP.Agendamento.Dados.PacienteSet Agendamento_Paciente(int id)
    {
        return base.Channel.Agendamento_Paciente(id);
    }
    
    public string[] RH_MedicoEspecialidade(int cod_especialidade)
    {
        return base.Channel.RH_MedicoEspecialidade(cod_especialidade);
    }
    
    public string[] RH_Especialidade()
    {
        return base.Channel.RH_Especialidade();
    }
    
    public string[] Administracao_PlanoSaude()
    {
        return base.Channel.Administracao_PlanoSaude();
    }
    
    public int Financeiro_SolicitarPagamento()
    {
        return base.Channel.Financeiro_SolicitarPagamento();
    }
}
