//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("erp_agendamentoModel", "FK_PacienteAgendamento", "PacienteSet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ERP.Agendamento.Models.PacienteSet), "AgendamentoSet", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ERP.Agendamento.Models.AgendamentoSet), true)]

#endregion

namespace ERP.Agendamento.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class erp_agendamentoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new erp_agendamentoEntities object using the connection string found in the 'erp_agendamentoEntities' section of the application configuration file.
        /// </summary>
        public erp_agendamentoEntities() : base("name=erp_agendamentoEntities", "erp_agendamentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new erp_agendamentoEntities object.
        /// </summary>
        public erp_agendamentoEntities(string connectionString) : base(connectionString, "erp_agendamentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new erp_agendamentoEntities object.
        /// </summary>
        public erp_agendamentoEntities(EntityConnection connection) : base(connection, "erp_agendamentoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AgendamentoSet> AgendamentoSets
        {
            get
            {
                if ((_AgendamentoSets == null))
                {
                    _AgendamentoSets = base.CreateObjectSet<AgendamentoSet>("AgendamentoSets");
                }
                return _AgendamentoSets;
            }
        }
        private ObjectSet<AgendamentoSet> _AgendamentoSets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PacienteSet> PacienteSets
        {
            get
            {
                if ((_PacienteSets == null))
                {
                    _PacienteSets = base.CreateObjectSet<PacienteSet>("PacienteSets");
                }
                return _PacienteSets;
            }
        }
        private ObjectSet<PacienteSet> _PacienteSets;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AgendamentoSets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAgendamentoSets(AgendamentoSet agendamentoSet)
        {
            base.AddObject("AgendamentoSets", agendamentoSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PacienteSets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPacienteSets(PacienteSet pacienteSet)
        {
            base.AddObject("PacienteSets", pacienteSet);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="erp_agendamentoModel", Name="AgendamentoSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AgendamentoSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AgendamentoSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="datahora">Initial value of the Datahora property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        /// <param name="paciente_Id">Initial value of the Paciente_Id property.</param>
        /// <param name="medico_Id">Initial value of the Medico_Id property.</param>
        public static AgendamentoSet CreateAgendamentoSet(global::System.Int32 id, global::System.DateTime datahora, global::System.String descricao, global::System.String estado, global::System.Int32 paciente_Id, global::System.Int32 medico_Id)
        {
            AgendamentoSet agendamentoSet = new AgendamentoSet();
            agendamentoSet.Id = id;
            agendamentoSet.Datahora = datahora;
            agendamentoSet.Descricao = descricao;
            agendamentoSet.Estado = estado;
            agendamentoSet.Paciente_Id = paciente_Id;
            agendamentoSet.Medico_Id = medico_Id;
            return agendamentoSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Datahora
        {
            get
            {
                return _Datahora;
            }
            set
            {
                OnDatahoraChanging(value);
                ReportPropertyChanging("Datahora");
                _Datahora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Datahora");
                OnDatahoraChanged();
            }
        }
        private global::System.DateTime _Datahora;
        partial void OnDatahoraChanging(global::System.DateTime value);
        partial void OnDatahoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Paciente_Id
        {
            get
            {
                return _Paciente_Id;
            }
            set
            {
                OnPaciente_IdChanging(value);
                ReportPropertyChanging("Paciente_Id");
                _Paciente_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Paciente_Id");
                OnPaciente_IdChanged();
            }
        }
        private global::System.Int32 _Paciente_Id;
        partial void OnPaciente_IdChanging(global::System.Int32 value);
        partial void OnPaciente_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Medico_Id
        {
            get
            {
                return _Medico_Id;
            }
            set
            {
                OnMedico_IdChanging(value);
                ReportPropertyChanging("Medico_Id");
                _Medico_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Medico_Id");
                OnMedico_IdChanged();
            }
        }
        private global::System.Int32 _Medico_Id;
        partial void OnMedico_IdChanging(global::System.Int32 value);
        partial void OnMedico_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Especialidade
        {
            get
            {
                return _Especialidade;
            }
            set
            {
                OnEspecialidadeChanging(value);
                ReportPropertyChanging("Especialidade");
                _Especialidade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Especialidade");
                OnEspecialidadeChanged();
            }
        }
        private global::System.String _Especialidade;
        partial void OnEspecialidadeChanging(global::System.String value);
        partial void OnEspecialidadeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("erp_agendamentoModel", "FK_PacienteAgendamento", "PacienteSet")]
        public PacienteSet PacienteSet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PacienteSet>("erp_agendamentoModel.FK_PacienteAgendamento", "PacienteSet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PacienteSet>("erp_agendamentoModel.FK_PacienteAgendamento", "PacienteSet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PacienteSet> PacienteSetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PacienteSet>("erp_agendamentoModel.FK_PacienteAgendamento", "PacienteSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PacienteSet>("erp_agendamentoModel.FK_PacienteAgendamento", "PacienteSet", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="erp_agendamentoModel", Name="PacienteSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PacienteSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PacienteSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="rg">Initial value of the Rg property.</param>
        /// <param name="cpf">Initial value of the Cpf property.</param>
        /// <param name="sexo">Initial value of the Sexo property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        /// <param name="peso">Initial value of the Peso property.</param>
        /// <param name="altura">Initial value of the Altura property.</param>
        /// <param name="tipoSanguineo">Initial value of the TipoSanguineo property.</param>
        /// <param name="afiliacaoMae">Initial value of the AfiliacaoMae property.</param>
        /// <param name="enderecoResidencial">Initial value of the EnderecoResidencial property.</param>
        public static PacienteSet CreatePacienteSet(global::System.Int32 id, global::System.String nome, global::System.String rg, global::System.String cpf, global::System.String sexo, global::System.DateTime dataNascimento, global::System.Int32 peso, global::System.Int32 altura, global::System.String tipoSanguineo, global::System.String afiliacaoMae, global::System.String enderecoResidencial)
        {
            PacienteSet pacienteSet = new PacienteSet();
            pacienteSet.Id = id;
            pacienteSet.Nome = nome;
            pacienteSet.Rg = rg;
            pacienteSet.Cpf = cpf;
            pacienteSet.Sexo = sexo;
            pacienteSet.DataNascimento = dataNascimento;
            pacienteSet.Peso = peso;
            pacienteSet.Altura = altura;
            pacienteSet.TipoSanguineo = tipoSanguineo;
            pacienteSet.AfiliacaoMae = afiliacaoMae;
            pacienteSet.EnderecoResidencial = enderecoResidencial;
            return pacienteSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rg
        {
            get
            {
                return _Rg;
            }
            set
            {
                OnRgChanging(value);
                ReportPropertyChanging("Rg");
                _Rg = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rg");
                OnRgChanged();
            }
        }
        private global::System.String _Rg;
        partial void OnRgChanging(global::System.String value);
        partial void OnRgChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cpf
        {
            get
            {
                return _Cpf;
            }
            set
            {
                OnCpfChanging(value);
                ReportPropertyChanging("Cpf");
                _Cpf = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cpf");
                OnCpfChanged();
            }
        }
        private global::System.String _Cpf;
        partial void OnCpfChanging(global::System.String value);
        partial void OnCpfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.String _Sexo;
        partial void OnSexoChanging(global::System.String value);
        partial void OnSexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Peso
        {
            get
            {
                return _Peso;
            }
            set
            {
                OnPesoChanging(value);
                ReportPropertyChanging("Peso");
                _Peso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Peso");
                OnPesoChanged();
            }
        }
        private global::System.Int32 _Peso;
        partial void OnPesoChanging(global::System.Int32 value);
        partial void OnPesoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Altura
        {
            get
            {
                return _Altura;
            }
            set
            {
                OnAlturaChanging(value);
                ReportPropertyChanging("Altura");
                _Altura = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Altura");
                OnAlturaChanged();
            }
        }
        private global::System.Int32 _Altura;
        partial void OnAlturaChanging(global::System.Int32 value);
        partial void OnAlturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoSanguineo
        {
            get
            {
                return _TipoSanguineo;
            }
            set
            {
                OnTipoSanguineoChanging(value);
                ReportPropertyChanging("TipoSanguineo");
                _TipoSanguineo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TipoSanguineo");
                OnTipoSanguineoChanged();
            }
        }
        private global::System.String _TipoSanguineo;
        partial void OnTipoSanguineoChanging(global::System.String value);
        partial void OnTipoSanguineoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AfiliacaoPai
        {
            get
            {
                return _AfiliacaoPai;
            }
            set
            {
                OnAfiliacaoPaiChanging(value);
                ReportPropertyChanging("AfiliacaoPai");
                _AfiliacaoPai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AfiliacaoPai");
                OnAfiliacaoPaiChanged();
            }
        }
        private global::System.String _AfiliacaoPai;
        partial void OnAfiliacaoPaiChanging(global::System.String value);
        partial void OnAfiliacaoPaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AfiliacaoMae
        {
            get
            {
                return _AfiliacaoMae;
            }
            set
            {
                OnAfiliacaoMaeChanging(value);
                ReportPropertyChanging("AfiliacaoMae");
                _AfiliacaoMae = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AfiliacaoMae");
                OnAfiliacaoMaeChanged();
            }
        }
        private global::System.String _AfiliacaoMae;
        partial void OnAfiliacaoMaeChanging(global::System.String value);
        partial void OnAfiliacaoMaeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EnderecoResidencial
        {
            get
            {
                return _EnderecoResidencial;
            }
            set
            {
                OnEnderecoResidencialChanging(value);
                ReportPropertyChanging("EnderecoResidencial");
                _EnderecoResidencial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EnderecoResidencial");
                OnEnderecoResidencialChanged();
            }
        }
        private global::System.String _EnderecoResidencial;
        partial void OnEnderecoResidencialChanging(global::System.String value);
        partial void OnEnderecoResidencialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelefoneResidencial
        {
            get
            {
                return _TelefoneResidencial;
            }
            set
            {
                OnTelefoneResidencialChanging(value);
                ReportPropertyChanging("TelefoneResidencial");
                _TelefoneResidencial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelefoneResidencial");
                OnTelefoneResidencialChanged();
            }
        }
        private global::System.String _TelefoneResidencial;
        partial void OnTelefoneResidencialChanging(global::System.String value);
        partial void OnTelefoneResidencialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EnderecoComercial
        {
            get
            {
                return _EnderecoComercial;
            }
            set
            {
                OnEnderecoComercialChanging(value);
                ReportPropertyChanging("EnderecoComercial");
                _EnderecoComercial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EnderecoComercial");
                OnEnderecoComercialChanged();
            }
        }
        private global::System.String _EnderecoComercial;
        partial void OnEnderecoComercialChanging(global::System.String value);
        partial void OnEnderecoComercialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelefoneComercial
        {
            get
            {
                return _TelefoneComercial;
            }
            set
            {
                OnTelefoneComercialChanging(value);
                ReportPropertyChanging("TelefoneComercial");
                _TelefoneComercial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelefoneComercial");
                OnTelefoneComercialChanged();
            }
        }
        private global::System.String _TelefoneComercial;
        partial void OnTelefoneComercialChanging(global::System.String value);
        partial void OnTelefoneComercialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelefoneCelular
        {
            get
            {
                return _TelefoneCelular;
            }
            set
            {
                OnTelefoneCelularChanging(value);
                ReportPropertyChanging("TelefoneCelular");
                _TelefoneCelular = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelefoneCelular");
                OnTelefoneCelularChanged();
            }
        }
        private global::System.String _TelefoneCelular;
        partial void OnTelefoneCelularChanging(global::System.String value);
        partial void OnTelefoneCelularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Convenio
        {
            get
            {
                return _Convenio;
            }
            set
            {
                OnConvenioChanging(value);
                ReportPropertyChanging("Convenio");
                _Convenio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Convenio");
                OnConvenioChanged();
            }
        }
        private Nullable<global::System.Int32> _Convenio;
        partial void OnConvenioChanging(Nullable<global::System.Int32> value);
        partial void OnConvenioChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("erp_agendamentoModel", "FK_PacienteAgendamento", "AgendamentoSet")]
        public EntityCollection<AgendamentoSet> AgendamentoSets
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AgendamentoSet>("erp_agendamentoModel.FK_PacienteAgendamento", "AgendamentoSet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AgendamentoSet>("erp_agendamentoModel.FK_PacienteAgendamento", "AgendamentoSet", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
