//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace ERP.Agendamento.Serviços.Utils.Administracao_Services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdministracaoWSSoap", Namespace="http://localhost/")]
    public partial class AdministracaoWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListaServicosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaConveniosOperationCompleted;
        
        private System.Threading.SendOrPostCallback DadosClinicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaDescontosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaDescontosConveniosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdministracaoWS() {
            this.Url = global::ERP.Agendamento.Serviços.Utils.Properties.Settings.Default.ERP_Agendamento_Serviços_Utils_Administracao_Services_AdministracaoWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListaServicosCompletedEventHandler ListaServicosCompleted;
        
        /// <remarks/>
        public event ListaConveniosCompletedEventHandler ListaConveniosCompleted;
        
        /// <remarks/>
        public event DadosClinicaCompletedEventHandler DadosClinicaCompleted;
        
        /// <remarks/>
        public event ListaDescontosCompletedEventHandler ListaDescontosCompleted;
        
        /// <remarks/>
        public event ListaDescontosConveniosCompletedEventHandler ListaDescontosConveniosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/ListaServicos", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ListaServicos() {
            object[] results = this.Invoke("ListaServicos", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListaServicosAsync() {
            this.ListaServicosAsync(null);
        }
        
        /// <remarks/>
        public void ListaServicosAsync(object userState) {
            if ((this.ListaServicosOperationCompleted == null)) {
                this.ListaServicosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaServicosOperationCompleted);
            }
            this.InvokeAsync("ListaServicos", new object[0], this.ListaServicosOperationCompleted, userState);
        }
        
        private void OnListaServicosOperationCompleted(object arg) {
            if ((this.ListaServicosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaServicosCompleted(this, new ListaServicosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/ListaConvenios", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ListaConvenios() {
            object[] results = this.Invoke("ListaConvenios", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListaConveniosAsync() {
            this.ListaConveniosAsync(null);
        }
        
        /// <remarks/>
        public void ListaConveniosAsync(object userState) {
            if ((this.ListaConveniosOperationCompleted == null)) {
                this.ListaConveniosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaConveniosOperationCompleted);
            }
            this.InvokeAsync("ListaConvenios", new object[0], this.ListaConveniosOperationCompleted, userState);
        }
        
        private void OnListaConveniosOperationCompleted(object arg) {
            if ((this.ListaConveniosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaConveniosCompleted(this, new ListaConveniosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/DadosClinica", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable DadosClinica() {
            object[] results = this.Invoke("DadosClinica", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void DadosClinicaAsync() {
            this.DadosClinicaAsync(null);
        }
        
        /// <remarks/>
        public void DadosClinicaAsync(object userState) {
            if ((this.DadosClinicaOperationCompleted == null)) {
                this.DadosClinicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDadosClinicaOperationCompleted);
            }
            this.InvokeAsync("DadosClinica", new object[0], this.DadosClinicaOperationCompleted, userState);
        }
        
        private void OnDadosClinicaOperationCompleted(object arg) {
            if ((this.DadosClinicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DadosClinicaCompleted(this, new DadosClinicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/ListaDescontos", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ListaDescontos() {
            object[] results = this.Invoke("ListaDescontos", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListaDescontosAsync() {
            this.ListaDescontosAsync(null);
        }
        
        /// <remarks/>
        public void ListaDescontosAsync(object userState) {
            if ((this.ListaDescontosOperationCompleted == null)) {
                this.ListaDescontosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaDescontosOperationCompleted);
            }
            this.InvokeAsync("ListaDescontos", new object[0], this.ListaDescontosOperationCompleted, userState);
        }
        
        private void OnListaDescontosOperationCompleted(object arg) {
            if ((this.ListaDescontosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaDescontosCompleted(this, new ListaDescontosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/ListaDescontosConvenios", RequestNamespace="http://localhost/", ResponseNamespace="http://localhost/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ListaDescontosConvenios(int codigoConvenio) {
            object[] results = this.Invoke("ListaDescontosConvenios", new object[] {
                        codigoConvenio});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ListaDescontosConveniosAsync(int codigoConvenio) {
            this.ListaDescontosConveniosAsync(codigoConvenio, null);
        }
        
        /// <remarks/>
        public void ListaDescontosConveniosAsync(int codigoConvenio, object userState) {
            if ((this.ListaDescontosConveniosOperationCompleted == null)) {
                this.ListaDescontosConveniosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaDescontosConveniosOperationCompleted);
            }
            this.InvokeAsync("ListaDescontosConvenios", new object[] {
                        codigoConvenio}, this.ListaDescontosConveniosOperationCompleted, userState);
        }
        
        private void OnListaDescontosConveniosOperationCompleted(object arg) {
            if ((this.ListaDescontosConveniosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaDescontosConveniosCompleted(this, new ListaDescontosConveniosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListaServicosCompletedEventHandler(object sender, ListaServicosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaServicosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaServicosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListaConveniosCompletedEventHandler(object sender, ListaConveniosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaConveniosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaConveniosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DadosClinicaCompletedEventHandler(object sender, DadosClinicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DadosClinicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DadosClinicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListaDescontosCompletedEventHandler(object sender, ListaDescontosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaDescontosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaDescontosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListaDescontosConveniosCompletedEventHandler(object sender, ListaDescontosConveniosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaDescontosConveniosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaDescontosConveniosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591