//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace ERP.Agendamento.Serviços.Utils.RH_Servicos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RH_ServicoSoap", Namespace="http://localhost:3001/")]
    public partial class RH_Servico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback buscaFuncionariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscaDadosFuncionariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscaPagamentosOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscaFolhaPagamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscaBeneficioOperationCompleted;
        
        private System.Threading.SendOrPostCallback RH_MedicoEspecialidadeOperationCompleted;
        
        private System.Threading.SendOrPostCallback listEspecialidadeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RH_Servico() {
            this.Url = global::ERP.Agendamento.Serviços.Utils.Properties.Settings.Default.ERP_Agendamento_Serviços_Utils_RH_Servicos_RH_Servico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event buscaFuncionariosCompletedEventHandler buscaFuncionariosCompleted;
        
        /// <remarks/>
        public event buscaDadosFuncionariosCompletedEventHandler buscaDadosFuncionariosCompleted;
        
        /// <remarks/>
        public event buscaPagamentosCompletedEventHandler buscaPagamentosCompleted;
        
        /// <remarks/>
        public event buscaFolhaPagamentoCompletedEventHandler buscaFolhaPagamentoCompleted;
        
        /// <remarks/>
        public event buscaBeneficioCompletedEventHandler buscaBeneficioCompleted;
        
        /// <remarks/>
        public event RH_MedicoEspecialidadeCompletedEventHandler RH_MedicoEspecialidadeCompleted;
        
        /// <remarks/>
        public event listEspecialidadeCompletedEventHandler listEspecialidadeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3001/buscaFuncionarios", RequestNamespace="http://localhost:3001/", ResponseNamespace="http://localhost:3001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscaFuncionarios(string nome) {
            object[] results = this.Invoke("buscaFuncionarios", new object[] {
                        nome});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscaFuncionariosAsync(string nome) {
            this.buscaFuncionariosAsync(nome, null);
        }
        
        /// <remarks/>
        public void buscaFuncionariosAsync(string nome, object userState) {
            if ((this.buscaFuncionariosOperationCompleted == null)) {
                this.buscaFuncionariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaFuncionariosOperationCompleted);
            }
            this.InvokeAsync("buscaFuncionarios", new object[] {
                        nome}, this.buscaFuncionariosOperationCompleted, userState);
        }
        
        private void OnbuscaFuncionariosOperationCompleted(object arg) {
            if ((this.buscaFuncionariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscaFuncionariosCompleted(this, new buscaFuncionariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3001/buscaDadosFuncionarios", RequestNamespace="http://localhost:3001/", ResponseNamespace="http://localhost:3001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscaDadosFuncionarios(int idFuncionario) {
            object[] results = this.Invoke("buscaDadosFuncionarios", new object[] {
                        idFuncionario});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscaDadosFuncionariosAsync(int idFuncionario) {
            this.buscaDadosFuncionariosAsync(idFuncionario, null);
        }
        
        /// <remarks/>
        public void buscaDadosFuncionariosAsync(int idFuncionario, object userState) {
            if ((this.buscaDadosFuncionariosOperationCompleted == null)) {
                this.buscaDadosFuncionariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaDadosFuncionariosOperationCompleted);
            }
            this.InvokeAsync("buscaDadosFuncionarios", new object[] {
                        idFuncionario}, this.buscaDadosFuncionariosOperationCompleted, userState);
        }
        
        private void OnbuscaDadosFuncionariosOperationCompleted(object arg) {
            if ((this.buscaDadosFuncionariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscaDadosFuncionariosCompleted(this, new buscaDadosFuncionariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3001/buscaPagamentos", RequestNamespace="http://localhost:3001/", ResponseNamespace="http://localhost:3001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscaPagamentos(int idFunc, int mes, int ano) {
            object[] results = this.Invoke("buscaPagamentos", new object[] {
                        idFunc,
                        mes,
                        ano});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscaPagamentosAsync(int idFunc, int mes, int ano) {
            this.buscaPagamentosAsync(idFunc, mes, ano, null);
        }
        
        /// <remarks/>
        public void buscaPagamentosAsync(int idFunc, int mes, int ano, object userState) {
            if ((this.buscaPagamentosOperationCompleted == null)) {
                this.buscaPagamentosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaPagamentosOperationCompleted);
            }
            this.InvokeAsync("buscaPagamentos", new object[] {
                        idFunc,
                        mes,
                        ano}, this.buscaPagamentosOperationCompleted, userState);
        }
        
        private void OnbuscaPagamentosOperationCompleted(object arg) {
            if ((this.buscaPagamentosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscaPagamentosCompleted(this, new buscaPagamentosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3001/buscaFolhaPagamento", RequestNamespace="http://localhost:3001/", ResponseNamespace="http://localhost:3001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscaFolhaPagamento(int mes, int ano) {
            object[] results = this.Invoke("buscaFolhaPagamento", new object[] {
                        mes,
                        ano});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscaFolhaPagamentoAsync(int mes, int ano) {
            this.buscaFolhaPagamentoAsync(mes, ano, null);
        }
        
        /// <remarks/>
        public void buscaFolhaPagamentoAsync(int mes, int ano, object userState) {
            if ((this.buscaFolhaPagamentoOperationCompleted == null)) {
                this.buscaFolhaPagamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaFolhaPagamentoOperationCompleted);
            }
            this.InvokeAsync("buscaFolhaPagamento", new object[] {
                        mes,
                        ano}, this.buscaFolhaPagamentoOperationCompleted, userState);
        }
        
        private void OnbuscaFolhaPagamentoOperationCompleted(object arg) {
            if ((this.buscaFolhaPagamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscaFolhaPagamentoCompleted(this, new buscaFolhaPagamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3001/buscaBeneficio", RequestNamespace="http://localhost:3001/", ResponseNamespace="http://localhost:3001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet buscaBeneficio(int mes, int ano) {
            object[] results = this.Invoke("buscaBeneficio", new object[] {
                        mes,
                        ano});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void buscaBeneficioAsync(int mes, int ano) {
            this.buscaBeneficioAsync(mes, ano, null);
        }
        
        /// <remarks/>
        public void buscaBeneficioAsync(int mes, int ano, object userState) {
            if ((this.buscaBeneficioOperationCompleted == null)) {
                this.buscaBeneficioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaBeneficioOperationCompleted);
            }
            this.InvokeAsync("buscaBeneficio", new object[] {
                        mes,
                        ano}, this.buscaBeneficioOperationCompleted, userState);
        }
        
        private void OnbuscaBeneficioOperationCompleted(object arg) {
            if ((this.buscaBeneficioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscaBeneficioCompleted(this, new buscaBeneficioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3001/RH_MedicoEspecialidade", RequestNamespace="http://localhost:3001/", ResponseNamespace="http://localhost:3001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet RH_MedicoEspecialidade(int IdEspecialidade, System.DateTime data) {
            object[] results = this.Invoke("RH_MedicoEspecialidade", new object[] {
                        IdEspecialidade,
                        data});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RH_MedicoEspecialidadeAsync(int IdEspecialidade, System.DateTime data) {
            this.RH_MedicoEspecialidadeAsync(IdEspecialidade, data, null);
        }
        
        /// <remarks/>
        public void RH_MedicoEspecialidadeAsync(int IdEspecialidade, System.DateTime data, object userState) {
            if ((this.RH_MedicoEspecialidadeOperationCompleted == null)) {
                this.RH_MedicoEspecialidadeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRH_MedicoEspecialidadeOperationCompleted);
            }
            this.InvokeAsync("RH_MedicoEspecialidade", new object[] {
                        IdEspecialidade,
                        data}, this.RH_MedicoEspecialidadeOperationCompleted, userState);
        }
        
        private void OnRH_MedicoEspecialidadeOperationCompleted(object arg) {
            if ((this.RH_MedicoEspecialidadeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RH_MedicoEspecialidadeCompleted(this, new RH_MedicoEspecialidadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:3001/listEspecialidade", RequestNamespace="http://localhost:3001/", ResponseNamespace="http://localhost:3001/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet listEspecialidade() {
            object[] results = this.Invoke("listEspecialidade", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void listEspecialidadeAsync() {
            this.listEspecialidadeAsync(null);
        }
        
        /// <remarks/>
        public void listEspecialidadeAsync(object userState) {
            if ((this.listEspecialidadeOperationCompleted == null)) {
                this.listEspecialidadeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistEspecialidadeOperationCompleted);
            }
            this.InvokeAsync("listEspecialidade", new object[0], this.listEspecialidadeOperationCompleted, userState);
        }
        
        private void OnlistEspecialidadeOperationCompleted(object arg) {
            if ((this.listEspecialidadeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listEspecialidadeCompleted(this, new listEspecialidadeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void buscaFuncionariosCompletedEventHandler(object sender, buscaFuncionariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscaFuncionariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscaFuncionariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void buscaDadosFuncionariosCompletedEventHandler(object sender, buscaDadosFuncionariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscaDadosFuncionariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscaDadosFuncionariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void buscaPagamentosCompletedEventHandler(object sender, buscaPagamentosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscaPagamentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscaPagamentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void buscaFolhaPagamentoCompletedEventHandler(object sender, buscaFolhaPagamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscaFolhaPagamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscaFolhaPagamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void buscaBeneficioCompletedEventHandler(object sender, buscaBeneficioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscaBeneficioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscaBeneficioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RH_MedicoEspecialidadeCompletedEventHandler(object sender, RH_MedicoEspecialidadeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RH_MedicoEspecialidadeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RH_MedicoEspecialidadeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void listEspecialidadeCompletedEventHandler(object sender, listEspecialidadeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listEspecialidadeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listEspecialidadeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591